SET IDENTITY_INSERT [dbo].[Vehicles] ON
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (2, N'Fire Truck A', 1, 0, 1, 0, 1, 0, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (3, N'Fire Truck B', 0, 1, 0, 1, 0, 1, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (4, N'Fire Truck C', 1, 1, 1, 1, 1, 1, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (5, N'Fire Truck D', 0, 0, 0, 0, 0, 0, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (6, N'Fire Truck E', 1, 0, 1, 0, 1, 0, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (7, N'Fire Truck F', 0, 1, 0, 1, 0, 1, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (8, N'Fire Truck G', 1, 1, 1, 1, 1, 1, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (9, N'Fire Truck H', 0, 0, 0, 0, 0, 0, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (10, N'Fire Truck I', 1, 0, 1, 0, 1, 0, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (11, N'Fire Truck J', 0, 1, 0, 1, 0, 1, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (12, N'Fire Truck K', 1, 1, 1, 1, 1, 1, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (13, N'Fire Truck L', 0, 0, 0, 0, 0, 0, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (14, N'Fire Truck M', 1, 0, 1, 0, 1, 0, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (15, N'Fire Truck N', 0, 1, 0, 1, 0, 1, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (16, N'Fire Truck O', 1, 1, 1, 1, 1, 1, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (17, N'Fire Truck P', 0, 0, 0, 0, 0, 0, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (18, N'Fire Truck Q', 1, 0, 1, 0, 1, 0, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (19, N'Fire Truck R', 0, 1, 0, 1, 0, 1, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (20, N'Fire Truck S', 1, 1, 1, 1, 1, 1, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (21, N'Fire Truck T', 0, 0, 0, 0, 0, 0, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (22, N'Fire Truck U', 1, 0, 1, 0, 1, 0, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (23, N'Fire Truck V', 0, 1, 0, 1, 0, 1, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (24, N'Fire Truck W', 1, 1, 1, 1, 1, 1, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (25, N'Fire Truck X', 0, 0, 0, 0, 0, 0, 0)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (26, N'Fire Truck Y', 1, 0, 1, 0, 1, 0, 1)
INSERT INTO [dbo].[Vehicles] ([Id], [CarModel], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [isSunday]) VALUES (28, N'Fire Truck Z', 0, 1, 1, 0, 1, 0, 1)
SET IDENTITY_INSERT [dbo].[Vehicles] OFF
